### ISSUE TITLE
Overlapping posts

### ISSUE THREAD

**Issue by mgdesaix** [lucky-yoolk/tumblr-ethanol#2]
Hello, I really enjoy using the ethanol theme, it came highly rated to me from other friends.  The only difficulties I am having are with posts of videos or photos covering up text posts below them, I thought the "responsive" aspect took care of this?

**Comment by lucky-yoolk** [comment]
Hi, Could you provide me a link where this bug occurs, i've tried to reproduce the bug with no success.
Thx

**Comment by mgdesaix** [comment]
I don't remember posting this years ago but just found it and wanted it closed!
